server.port=8081
server.servlet.context-path=/myBoot
#\u4F7F\u7528\u7CFB\u7EDF\u9ED8\u8BA4\u7684\u5B57\u7B26\u8FC7\u6EE4\u5668
server.servlet.encoding.enabled=true
#\u6307\u5B9A\u5B57\u7B26\u96C6
server.servlet.encoding.charset=GBK
#\u8BBE\u7F6Erequest\u548Cresponse\u90FD\u4F7F\u7528\u8FD9\u4E2A\u5B57\u7B26\u96C6
server.servlet.encoding.force=true

