#\u914D\u7F6E\u89C6\u56FE\u89E3\u6790\u5668
#/\u4EE3\u8868web\u76EE\u5F55\u7684\u6839\uFF0C\u4E5F\u5C31\u662F--->src/main/webapp
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

server.port=9090
server.servlet.context-path=/myJsp